sudo: false
language: ruby
cache: bundler
install:
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle update sass-spec
rvm:
  - 2.4.1
gemfile: Gemfile
env:
  - MATHN=true RUBOCOP=false
  - MATHN=false RUBOCOP=false
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-21mode
    - rvm: jruby-9.0.0.0
